### PR TITLE
Migrate to libffi branch that is working on ARMv7 and ARM64

### PR DESCRIPTION
**Pull request by superdump**
From https://github.com/NativeScript/libffi.git . Discussion at
https://github.com/atgreen/libffi/issues/181#issuecomment-150174705

### CODE REVIEW

**Comment by stefanalund** [comment]
Testing this now as it is needed for Bowser to work on iPhone 6s as well as older 32-bit devices.

**Comment by stefanalund** [comment]
Confirmed that Bowser works on iPhone 5 (32-bit) as well as newest iPhone 6s. :+1:

**Comment by stefanalund** [comment]
Now also confirmed that it works using the `openwebrtc-daemon` on OS X El Cap.

**Comment by superdump** [comment]
We now just need to test on Android and Linux and then we can merge it!

**Pull request closed without merging**
