### PR TITLE
libffi: set FFI_MMAP_EXEC_WRIT and unset FFI_MMAP_EXEC_SELINUX on Android

### PR DESCRIPTION
**Pull request by Rugvip**
This fixes a crash on Android
Found here: https://github.com/frida/frida/blob/d3679e46df36986beca03da59be7acd691b6babe/releng/config.site.in#L119 (thanks to @oleavr)

### CODE REVIEW

**Comment by sdroege** [comment]
Makes sense but do you have some more details about the crash? On which versions of Android does it happen, in which situations?

**Comment by sdroege** [comment]
And did someone report it to libffi?

**Comment by Rugvip** [comment]
This was the error: `signal 11 (SIGSEGV), code -6 (SI_TKILL), fault addr 0x9fa79b00``
Same as the error in EricssonResearch/openwebrtc#177, which is the one it fixes
It happens when trying to call a closure created by libffi, on at least Lollipop and KitKat.

**Comment by sdroege** [comment]
In that ticket it's all about iOS. Do you have a backtrace for Android?

**Comment by Rugvip** [comment]
I don't, but it's identical to the seconds comment, segfault when calling the callback in g_task_return_now.

**Comment by superdump** [comment]
LGTM. @Rugvip can you report this upstream and merge this?

**Pull request merged**
