### PR TITLE
openwebrtc.recipe: Fix libopenwebrtc_bridge_jni.so (Android)

### PR DESCRIPTION
**Pull request by nirbheek**
libopenwebrtc_bridge_jni.so that it depends on libopenwebrtc_jni.so instead of
bundling it statically. This allows openwebrtc_bridge.jar to depend on
openwebrtc.jar.

Change requested by rugvip

### CODE REVIEW

**Comment by Rugvip** [comment]
As discused on IRC, this does make openwebrtc_bridge.so depend on the GStreamer etc. But any dependency that is common between both openwebrtc.so and openwebrtc_bridge.so will be included in openwebrtc_bridge.so, but it should really just depend on openwebrtc.so for those dependencies.

The problem with this except for wasted space is the type registry in GLib, which is completely broken.

**Comment by nirbheek** [comment]
@Rugvip libopenwebrtc_bridge_jni.so now doesn't include a second copy of glib (or any other library, such as libiconv, etc).

**Comment by Rugvip** [comment]
Yup, seems like it's working now :smiley:
I'm running into this problem though: EricssonResearch/openwebrtc#177 :neutral_face:

**Comment by nirbheek** [comment]
Let's push this PR then?

**Comment by Rugvip** [comment]
merged

**Pull request closed without merging**
