### PR TITLE
packages/base-system: add back libiconv on iOS

### PR DESCRIPTION
**Pull request by alessandrod**

### CODE REVIEW

**Comment by alessandrod** [comment]
I can see that the dependency has been added and then removed recently. Without it iOS compilation fails for me. Am I missing something?

**Comment by superdump** [comment]
Poke Matthew - it seems it was removed intentionally as its now included by the platform. Maybe it needs some platform SDK version checking to decide whether to add it or not.

**Comment by sdroege** [comment]
It's part of the platform, yes, and should just work without. How is something failing without building it ourselves?

**Comment by superdump** [comment]
cerbero doesn't fail. Building apps fails it seems. Can you try adding the system libiconv to the xcode project?

**Comment by stefanalund** [comment]
That solves the problem for me.

**Comment by sdroege** [comment]
Yes that's what should be done, see e.g. http://cgit.freedesktop.org/~slomo/gst-sdk-tutorials/commit/gst-sdk/tutorials/xcode%20iOS?id=77b2656d6d661f422c0ddd1b4357f829a0ef9e5d

**Comment by superdump** [comment]
Closing.

**Pull request closed without merging**
